name: Compile and test

on:
  push:
    paths:
      - 'src/**'
      - 'pom.xml'
      - '.github/workflows/maven.yml'

  pull_request:
    paths:
      - 'src/**'
      - 'pom.xml'

jobs:
  compile:
    name: Maven compiler
    runs-on: ubuntu-latest
    steps:
      # 1. 检出代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. 设置 Java 17 JDK (AdoptOpenJDK)
      - name: Java 17 setup
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      # 3. 缓存 Maven 依赖
      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      # 4. 使用 Maven 编译
      - name: Build via Maven
        run: mvn package -B --file pom.xml -DdisableXmlReport=true

      # 5. 上传构建的 JAR 文件
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: minecraft-plugin
          path: target/*.jar  # 确保上传编译的 JAR 文件
